import {
  mdiAccountCircleOutline,
  mdiAlertCircleOutline,
  mdiArrowDown,
  mdiArrowUp,
  mdiBookmarkOutline,
  mdiContentSaveOutline,
  mdiCheckCircleOutline,
  mdiCloseCircleOutline,
  mdiPlus,
  mdiCloudUploadOutline,
  mdiCrop,
  mdiTableColumn,
  mdiCogOutline,
  mdiDotsHorizontal,
  mdiEyeOutline,
  mdiFileOutline,
  mdiFlipHorizontal,
  mdiFilterVariant,
  mdiInboxOutline,
  mdiInformationOutline,
  mdiHelpCircleOutline,
  mdiLogoutVariant,
  mdiPaletteOutline,
  mdiPencilOutline,
  mdiImageOutline,
  mdiRefresh,
  mdiRotateLeft,
  mdiRotateRight,
  mdiStarOutline,
  mdiTrashCanOutline,
  mdiViewDashboardOutline,
  mdiWifiOff,
  mdiMagnifyMinusOutline,
  mdiMagnifyPlusOutline,
} from '@mdi/js'

export const velaIconAliases = Object.freeze({
  account: mdiAccountCircleOutline,
  checkCircle: mdiCheckCircleOutline,
  closeCircle: mdiCloseCircleOutline,
  arrowDown: mdiArrowDown,
  arrowUp: mdiArrowUp,
  add: mdiPlus,
  bookmarkOutline: mdiBookmarkOutline,
  columns: mdiTableColumn,
  crop: mdiCrop,
  dashboard: mdiViewDashboardOutline,
  delete: mdiTrashCanOutline,
  edit: mdiPencilOutline,
  empty: mdiInboxOutline,
  error: mdiAlertCircleOutline,
  file: mdiFileOutline,
  flipHorizontal: mdiFlipHorizontal,
  filter: mdiFilterVariant,
  info: mdiInformationOutline,
  image: mdiImageOutline,
  helpCircle: mdiHelpCircleOutline,
  logout: mdiLogoutVariant,
  menuMore: mdiDotsHorizontal,
  offline: mdiWifiOff,
  palette: mdiPaletteOutline,
  refresh: mdiRefresh,
  rotateLeft: mdiRotateLeft,
  rotateRight: mdiRotateRight,
  settings: mdiCogOutline,
  save: mdiContentSaveOutline,
  star: mdiStarOutline,
  upload: mdiCloudUploadOutline,
  view: mdiEyeOutline,
  zoomIn: mdiMagnifyPlusOutline,
  zoomOut: mdiMagnifyMinusOutline,
})
