export const velaBreakpoints = Object.freeze({
  xs: 0,
  sm: 600,
  md: 960,
  lg: 1280,
  xl: 1920,
  xxl: 2560,
})

/** Numeric table metrics used by Vuetify's sticky-offset calculation and mirrored as CSS tokens. */
export const velaTableMetrics = Object.freeze({
  defaultMinWidth: 96,
  defaultMaxWidth: 384,
  actionWidth: 136,
  overflowTolerance: 2,
  resizeMinWidth: 64,
  resizeMaxWidth: 720,
  resizeStep: 16,
})

/** Shared semantic widths keep schema-driven tables consistent without page-local magic numbers. */
export const velaTableSemanticMetrics = Object.freeze({
  identity: Object.freeze({ min: 160, max: 384 }),
  media: Object.freeze({ min: 208, max: 352 }),
  status: Object.freeze({ min: 96, max: 144 }),
  boolean: Object.freeze({ min: 88, max: 120 }),
  number: Object.freeze({ min: 104, max: 160 }),
  currency: Object.freeze({ min: 120, max: 184 }),
  progress: Object.freeze({ min: 144, max: 192 }),
  trend: Object.freeze({ min: 128, max: 184 }),
  date: Object.freeze({ min: 128, max: 160 }),
  datetime: Object.freeze({ min: 168, max: 208 }),
})

/** Numeric feedback metrics for Vuetify props, mirrored below as CSS tokens. */
export const velaFeedbackMetrics = Object.freeze({
  loadingSpinnerSize: 36,
})

export const velaPalette = Object.freeze({
  indigo: Object.freeze({
    50: '#F7F2FF',
    100: '#EFE7FF',
    200: '#E0D2FF',
    300: '#C8B4FC',
    400: '#A78AF4',
    500: '#9169ED',
    600: '#7A4FE0',
    700: '#6740C4',
    800: '#5637A4',
    900: '#482F84',
  }),
  slate: Object.freeze({
    0: '#FFFFFF',
    50: '#F8FAFC',
    100: '#F1F5F9',
    200: '#E2E8F0',
    300: '#CBD5E1',
    400: '#94A3B8',
    500: '#64748B',
    600: '#475569',
    700: '#334155',
    800: '#1E293B',
    900: '#0F172A',
    950: '#080D18',
  }),
  emerald: Object.freeze({
    50: '#ECFDF5',
    500: '#10B981',
    600: '#059669',
    700: '#047857',
  }),
  amber: Object.freeze({
    50: '#FFFBEB',
    500: '#F59E0B',
    600: '#D97706',
    700: '#B45309',
  }),
  rose: Object.freeze({
    50: '#FFF1F2',
    500: '#F43F5E',
    600: '#E11D48',
    700: '#BE123C',
  }),
  blue: Object.freeze({
    50: '#EFF6FF',
    500: '#3B82F6',
    600: '#2563EB',
    700: '#1D4ED8',
  }),
})

export const velaThemeVariables = Object.freeze({
  'font-family-sans':
    "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  'font-family-mono': "'SFMono-Regular', Consolas, 'Liberation Mono', monospace",
  'font-size-xs': '0.75rem',
  'font-size-sm': '0.8125rem',
  'font-size-md': '0.875rem',
  'font-size-lg': '1rem',
  'font-size-xl': '1.125rem',
  'font-size-2xl': '1.375rem',
  'font-size-3xl': '1.75rem',
  'line-height-tight': 1.25,
  'line-height-body': 1.5,
  'font-weight-regular': 400,
  'font-weight-medium': 500,
  'font-weight-semibold': 600,
  'font-weight-bold': 700,
  'text-accent-mix': '62%',
  'root-font-size-small': '15px',
  'root-font-size-default': '16px',
  'root-font-size-large': '17px',
  'space-0': '0px',
  'space-1': '0.25rem',
  'space-2': '0.5rem',
  'space-3': '0.75rem',
  'space-4': '1rem',
  'space-5': '1.25rem',
  'space-6': '1.5rem',
  'space-8': '2rem',
  'space-10': '2.5rem',
  'space-12': '3rem',
  'radius-xs': '0.25rem',
  'radius-sm': '0.5rem',
  'radius-md': '0.625rem',
  'radius-lg': '0.75rem',
  'radius-xl': '1rem',
  'radius-pill': '9999px',
  'control-height-sm': '2rem',
  'control-height-md': '2.5rem',
  'control-height-lg': '3rem',
  'opacity-hover': 0.08,
  'opacity-focus': 0.12,
  'opacity-pressed': 0.16,
  'opacity-disabled': 0.38,
  'contrast-border-opacity': 0.28,
  'contrast-medium-emphasis-opacity': 0.88,
  'contrast-high-emphasis-opacity': 1,
  'focus-outline-width': '0.125rem',
  'focus-outline-width-high': '0.1875rem',
  'surface-opacity-strong': 0.96,
  'shadow-card': '0 0.125rem 0.75rem rgba(var(--v-shadow-color), 0.08)',
  'shadow-floating': '0 0.375rem 1.5rem rgba(var(--v-shadow-color), 0.12)',
  'shadow-overlay': '0 1rem 3rem rgba(var(--v-shadow-color), 0.22)',
  'control-surface-opacity': 0.72,
  'control-hover-border-opacity': 0.42,
  'control-error-shadow': '0 0 0 0.1875rem rgba(var(--v-theme-error), var(--v-focus-opacity))',
  'button-spinner-size': '1rem',
  'avatar-initial-font-size': 'var(--v-font-size-xs)',
  'avatar-tint-opacity': 0.08,
  'avatar-border-opacity': 0.14,
  'avatar-shadow': '0 0.125rem 0.375rem rgba(var(--v-shadow-color), 0.07)',
  'motion-duration-fast': '120ms',
  'motion-duration-standard': '200ms',
  'motion-duration-slow': '320ms',
  'motion-duration-none': '0.01ms',
  'motion-easing-standard': 'cubic-bezier(0.2, 0, 0, 1)',
  'motion-easing-emphasized': 'cubic-bezier(0.2, 0, 0, 1.2)',
  'table-overflow-tolerance': `${velaTableMetrics.overflowTolerance}px`,
  'table-column-min': `${velaTableMetrics.defaultMinWidth / 16}rem`,
  'table-column-max': `${velaTableMetrics.defaultMaxWidth / 16}rem`,
  'table-action-width': `${velaTableMetrics.actionWidth / 16}rem`,
  'table-resize-handle-width': '0.75rem',
  'table-pinned-shadow': '-0.5rem 0 1rem -0.75rem rgba(var(--v-shadow-color), 0.28)',
  'table-pinned-border-opacity': 0.12,
  'table-shell-shadow': '0 0.5rem 1.75rem rgba(var(--v-shadow-color), 0.055)',
  'table-font-size': 'var(--v-font-size-sm)',
  'table-header-font-size': 'var(--v-font-size-xs)',
  'table-header-height': '3rem',
  'table-row-height-compact': '2.75rem',
  'table-row-height-comfortable': '3.25rem',
  'table-row-height-default': '3.5rem',
  'table-identity-avatar-size': '2.125rem',
  'table-cell-visual-size': '1.75rem',
  'table-cell-icon-size': '0.9375rem',
  'table-cell-visual-tint-opacity': 0.09,
  'table-cell-visual-border-opacity': 0.12,
  'table-media-width': '3rem',
  'table-media-height': '2.25rem',
  'table-media-background-opacity': 0.045,
  'table-media-border-opacity': 0.14,
  'table-progress-width': '7rem',
  'table-progress-height': '0.25rem',
  'table-progress-track-opacity': 0.12,
  'table-progress-glow': '0 0.125rem 0.5rem rgba(var(--va-table-cell-tone), 0.18)',
  'table-trend-icon-size': '1rem',
  'table-trend-tint-opacity': 0.08,
  'table-trend-border-opacity': 0.3,
  'table-row-accent-width': '0.125rem',
  'table-header-tint-opacity': 0.055,
  'table-header-border-opacity': 0.18,
  'table-row-hover-opacity': 0.045,
  'table-row-selected-opacity': 0.09,
  'table-row-focus-opacity': 0.12,
  'table-body-height': 'min(35rem, 60vh)',
  'row-actions-menu-width': '11rem',
  'data-pager-height': '3rem',
  'data-pager-select-width': '5rem',
  'data-pager-jump-width': '5rem',
  'data-pager-tint-opacity': 0.025,
  'data-saved-view-width': '22rem',
  'data-saved-view-list-height': '20rem',
  'tag-height': '1.5rem',
  'tag-icon-size': '0.875rem',
  'tag-border-mix': '14%',
  'tag-shadow': '0 0.125rem 0.375rem rgba(var(--v-shadow-color), 0.055)',
  'filter-bar-tint-opacity': 0.035,
  'filter-divider-opacity': 0.18,
  'filter-bar-shadow': '0 0.375rem 1.5rem rgba(var(--v-shadow-color), 0.045)',
  'filter-sheet-max-height': '82dvh',
  'state-view-min-height': '18rem',
  'state-view-max-width': '34rem',
  'state-view-visual-size': '6.5rem',
  'state-view-icon-size': '2.125rem',
  'state-view-decoration-size': '10rem',
  'state-view-pattern-size': '1.25rem',
  'state-view-pattern-opacity': 0.05,
  'state-view-tint-opacity': 0.09,
  'state-view-ring-opacity': 0.18,
  'state-view-glow': '0 1.25rem 3rem rgba(var(--va-state-tone), 0.18)',
  'form-section-tint-opacity': 0.035,
  'form-section-border-opacity': 0.16,
  'form-section-marker-size': '2.25rem',
  'form-section-shadow': '0 0.375rem 1.5rem rgba(var(--v-shadow-color), 0.04)',
  'shell-sidebar-width': '16.25rem',
  'shell-sidebar-rail-width': '4.25rem',
  'shell-header-height': '4rem',
  'shell-content-max-width': '90rem',
  'shell-content-padding': '1.5rem',
  'shell-content-padding-compact': '1rem',
  'shell-content-padding-comfortable': '1.5rem',
  'shell-content-padding-spacious': '2rem',
  'shell-nav-item-height': '2.75rem',
  'shell-nav-item-gap': '0.375rem',
  'shell-nav-item-radius': '0.5rem',
  'shell-nav-icon-size': '1.25rem',
  'shell-nav-inline-padding': '1rem',
  'shell-nav-hover-offset': '0.125rem',
  'shell-nav-section-gap': '1.5rem',
  'shell-nav-section-opacity': 0.54,
  'shell-nav-scroll-fade-height': '2rem',
  'shell-nav-scroll-fade-layer': 2,
  'shell-nav-active-shadow': '0 0.25rem 0.875rem rgba(var(--v-theme-primary), 0.3)',
  'appearance-preview-nav-width': '28%',
  'appearance-preview-rail-width': '12%',
  'appearance-preview-topbar-height': '28%',
  'appearance-preview-topbar-indicator-start': '38%',
  'appearance-preview-content-split': '48%',
  'appearance-layout-preview-height': '6rem',
  'appearance-tabs-surface-opacity': 0.72,
  'appearance-hover-border-opacity': 0.46,
  'appearance-active-ring': '0 0 0 2px rgba(var(--v-theme-primary), var(--v-focus-opacity))',
  'appearance-swatch-ring': '0 0 0 1px rgba(var(--v-border-color), var(--v-border-opacity))',
  'appearance-swatch-active-ring': '0 0 0 2px rgb(var(--v-theme-primary))',
  'feedback-toast-max-width': '26rem',
  'feedback-toast-accent-width': '0.25rem',
  'feedback-loading-panel-max-width': '22rem',
  'feedback-loading-spinner-size': `${velaFeedbackMetrics.loadingSpinnerSize / 16}rem`,
  'feedback-loading-scrim-opacity': 0.56,
  'feedback-loading-track-shadow':
    'inset 0 0 0 1px rgba(var(--v-theme-primary), var(--v-focus-opacity))',
  'upload-dropzone-min-height': '9rem',
  'upload-dropzone-glow-opacity': 0.1,
  'upload-dropzone-border-opacity': 0.38,
  'upload-dropzone-focus-shadow':
    '0 0 0 0.1875rem rgba(var(--v-theme-primary), var(--v-focus-opacity)), 0 0.75rem 2rem rgba(var(--v-shadow-color), 0.08)',
  'upload-hover-offset': '-0.125rem',
  'upload-backdrop-blur': '0.5rem',
  'upload-preparing-opacity': 0.82,
  'upload-list-shadow': '0 0.5rem 1.5rem rgba(var(--v-shadow-color), 0.045)',
  'upload-gallery-min-width': '11rem',
  'upload-gallery-preview-height': '8.5rem',
  'upload-tile-shadow': '0 0.375rem 1.25rem rgba(var(--v-shadow-color), 0.055)',
  'upload-tile-hover-shadow': '0 0.75rem 2rem rgba(var(--v-shadow-color), 0.1)',
  'upload-tile-hover-border-opacity': 0.32,
  'upload-error-border-opacity': 0.36,
  'upload-preview-overlay-opacity': 0.68,
  'upload-preview-hover-scale': 1.035,
  'upload-progress-height': '0.1875rem',
  'upload-preview-min-height': '20rem',
  'upload-preview-max-height': '70vh',
  'upload-checker-opacity': 0.035,
  'upload-checker-size': '0.5rem',
  'upload-cropper-height': '26rem',
  'upload-cropper-min-height': '20rem',
  'upload-cropper-mobile-height': '20rem',
  'upload-cropper-glow-opacity': 0.1,
  'upload-toolbar-icon-size': '1rem',
  'upload-avatar-action-border': '0.125rem',
  'upload-avatar-action-offset': '0.25rem',
  'table-sticky-layer': 1,
  'z-dropdown': 1000,
  'z-sticky': 1020,
  'z-overlay': 1040,
  'z-modal': 1060,
  'z-toast': 1080,
})

export const velaShellMetrics = Object.freeze({
  sidebarWidth: 260,
  sidebarRailWidth: 68,
  headerHeight: 64,
  contentMaxWidth: 1440,
})

export type VelaThemeVariable = keyof typeof velaThemeVariables
